Improved error messages for dev scripts
Currently the format and autogenerate_files.py scripts fail with
unuseful error messages if run outside of a nix shell.
We are currently assuming developers to use nix.
This commit adds some error messages nudging the user to install
nix and install the project's dependencies through nix.

Signed-off-by: Matthias J. Kannwischer <matthias@kannwischer.eu>

diff --git a/scripts/format b/scripts/format
--- a/scripts/format
+++ b/scripts/format
@@ -20,15 +20,32 @@ info()
 }
 
 info "Formatting nix files"
+if ! command -v nixpkgs-fmt 2>&1 >/dev/null; then
+  echo "nixpkgs-fmt not found. Are you running in a nix shell? See BUILDING.md."
+  exit 1
+fi
+
 nixpkgs-fmt "$ROOT"
 
 info "Formatting shell scripts"
+if ! command -v shfmt 2>&1 >/dev/null; then
+  echo "shfmt not found. Are you running in a nix shell? See BUILDING.md."
+  exit 1
+fi
 shfmt -s -w -l -i 2 -ci -fn $(shfmt -f $(git grep -l '' :/))
 
 info "Formatting python scripts"
+if ! command -v black 2>&1 >/dev/null; then
+  echo "black not found. Are you running in a nix shell? See BUILDING.md."
+  exit 1
+fi
 black --include "(scripts/tests|\.py$)" "$ROOT"
 
 info "Formatting c files"
+if ! command -v clang-format 2>&1 >/dev/null; then
+  echo "clang-format not found. Are you running in a nix shell? See BUILDING.md."
+  exit 1
+fi
 clang-format -i $(git ls-files ":/*.c" ":/*.h")
 
 info "Checking for eol"
